default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Learn4car1$
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: DevcamPortfolio_development


test:
  <<: *default
  database: DevcamPortfolio_test


production:
  <<: *default
  database: DevcamPortfolio_production
  username: DevcamPortfolio
  password: <%= ENV['DEVCAMPORTFOLIO_DATABASE_PASSWORD'] %>
